language: python
python:
    - 3.5

install:
    - cd src/
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - coverage run --source=obj -m pytest -v --ignore=env

after_success: coveralls

